<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
<PackageReference Include="NAudio" Version="2.*" />
    <PackageReference Include="NAudio.Vorbis" Version="1.*" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\header.jpg" />
  </ItemGroup>
</Project>
